name: Repository Dispatch

on:
  workflow_dispatch:
    inputs:
      release_candidate:
        type: boolean
        description: "Release Candidate"
        required: false
        default: false

env:
  RELEASE_VERSION: v23.3.23

jobs:
  dispatchEvent:
    permissions:
      contents: 'write'
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      if: inputs.release_candidate == false
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: phoban01/test-actions
        event-type: ocm-cli-release
        client-payload: '{"tag": "${{ env.RELEASE_VERSION }}"}'
